services:
  paises_api:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data:rw   # persistencia (csv/json)
    restart: unless-stopped

  # --- PREPROCESO G2: normaliza el CSV del grupo 2 (AUTOS) ---
  preprocess-g2:
    image: python:3.12-slim
    volumes:
      - ./scripts:/scripts:ro
      - ./datasets/g2:/work
    command: ["python","/scripts/normalize_csv.py","/work/raw.csv","/work/columns.map.json","/work/paises.csv"]
    restart: "no"

  # --- API G2 en 8010, con CSV normalizado ---
  api-g2:
    build: ./app
    container_name: paises-api-g2
    env_file: .env.g2
    ports:
      - "8010:8000"
    volumes:
      - ./data/g2:/app/data
      - ./datasets/g2/paises.csv:/app/paises.csv:ro
    depends_on:
      preprocess-g2:
        condition: service_completed_successfully
    restart: unless-stopped

  # --- PREPROCESO G3: normaliza el CSV del grupo 3 (COLEGIOS) ---
  preprocess-g3:
    image: python:3.12-slim
    volumes:
      - ./scripts:/scripts:ro
      - ./datasets/g3:/work
    command: ["python","/scripts/normalize_csv.py","/work/raw.csv","/work/columns.map.json","/work/paises.csv"]
    restart: "no"

  # --- API G3 en 8020, con CSV normalizado ---
  api-g3:
    build: ./app
    container_name: paises-api-g3
    env_file: .env.g3
    ports:
      - "8020:8000"
    volumes:
      - ./data/g3:/app/data
      - ./datasets/g3/paises.csv:/app/paises.csv:ro
    depends_on:
      preprocess-g3:
        condition: service_completed_successfully
    restart: unless-stopped
